baseURL = '//chenbrian.ca'
languageCode = 'en-us'
title = 'chenbrian'

# Theme to use
theme = "bettermotherfuckinghugowebsite"

# Pagination
paginate = 25
paginatePath = "page"


# enable last updated
enableGitInfo = true


[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']



# Google analytics
googleAnalytics = "G-B0ZFV4LTG2"

# Copyright
copyright = "© 2021 — Brian Chen — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "emacs"


# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"


# Menu
[menu]
# Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2
  [[menu.main]]
   url = "/tags/"
   name = "tags"
   weight = 3




# Footer
 [[menu.footer]]
  url = "https://github.com/ihasdapie/bettermotherfuckinghugowebsite/"
  name = "hugo theme"
  weight = 1

 [[menu.footer]]
   url = "https://github.com/ihasdapie"
   name = "GitHub"
   weight = 1


# Links format
[permalinks]
  posts = "/posts/:year/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"

[markup]
  [markup.goldmark.parser]
    block = true
    title = true


  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false




