baseURL = '//chenbrian.ca'
languageCode = 'en-us'
title = 'Chenbrian'

# Theme to use
theme = "bettermotherfuckinghugowebsite"

# Pagination
paginate = 3
paginatePath = "page"

# Google analytics
googleAnalytics = "G-B0ZFV4LTG2"

# Copyright
copyright = "© 2021 — Brian Chen — All rights reserved."

# Highlighting
pygmentsCodefences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "monokai"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  # Header
  [[menu.main]]
    url = "/posts/"
    name = "blog"
    weight = 1
  [[menu.main]]
    url = "/about/"
    name = "about"
    weight = 2

  # Footer
  [[menu.footer]]
    url = "https://github.com/ihasdapie"
    name = "GitHub"
    weight = 1


# Links format
[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  # Date format (default: Jan 2, 2006)
  # datefmt  = "Jan 2, 2006"
